import tkinter
window = tkinter.Tk()
window.geometry("300x400")

b1=tkinter.Button(window,text="boton1",width=10,height=5)
b2=tkinter.Button(window,text="boton1",width=10,height=5)
b3=tkinter.Button(window,text="boton1",width=10,height=5)
b4=tkinter.Button(window,text="boton1",width=10,height=5)
b5=tkinter.Button(window,text="boton1",width=10,height=5)
b6=tkinter.Button(window,text="boton1",width=10,height=5)
b7=tkinter.Button(window,text="boton1",width=10,height=5)
b8=tkinter.Button(window,text="boton1",width=10,height=5)
b9=tkinter.Button(window,text="boton1",width=10,height=5)
b10=tkinter.Button(window,text="boton1",width=10,height=5)
b11=tkinter.Button(window,text="boton1",width=10,height=5)
b12=tkinter.Button(window,text="boton1",width=10,height=5)
b13=tkinter.Button(window,text="boton1",width=10,height=5)
b14=tkinter.Button(window,text="boton1",width=10,height=5)
b15=tkinter.Button(window,text="boton1",width=10,height=5)
b16=tkinter.Button(window,text="boton1",width=10,height=5)

b[1].grid(row=0,column=0)
b[2].grid(row=0,column=1)
b[3].grid(row=0,column=3)
b[4].grid(row=0,column=4)
# b[5].grid(row=0,column=5)

window.mainloop()